import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import CustomThemeProvider from "@/components/(providers)/Themeproviders";
import { Toaster } from "@/components/ui/toaster";
import DesignerContextProvider from "@/components/context/DesignContext";
import NextTopLoader from "nextjs-toploader"
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Form Builder",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider
      afterSignOutUrl={"/"}
      signInFallbackRedirectUrl={"/"}
      signInForceRedirectUrl={"/"}
      signUpForceRedirectUrl={"/"}
    >
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
           <NextTopLoader/>
          <DesignerContextProvider>
          <CustomThemeProvider>
            {children}
            <Toaster/>
          </CustomThemeProvider>
          </DesignerContextProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
